import type {
  Command,
  ExecutionHistoryItem,
  ExecutionLogLine,
  HistoryStats,
  LiveExecution,
  Pipeline,
  Repository,
  RunQueueItem,
} from "@/components/command-hub/types"

export const repositories: Repository[] = [
  {
    name: "commander",
    path: "~/codes/commander",
    branch: "main",
    status: "active",
    tech: ["tauri", "react", "vite"],
    lastRun: "now",
    running: "dev: tauri",
  },
  {
    name: "billing-api",
    path: "~/codes/billing-api",
    branch: "release/2026.01",
    status: "idle",
    tech: ["node", "prisma"],
    lastRun: "20 min",
    running: "-",
  },
  {
    name: "ui-kit",
    path: "~/codes/ui-kit",
    branch: "design-refresh",
    status: "warn",
    tech: ["storybook", "ts"],
    lastRun: "yesterday",
    running: "tests",
  },
]

export const commands: Command[] = [
  {
    name: "Dev (Tauri)",
    command: "pnpm tauri dev",
    type: "run",
    status: "running",
    duration: "02:14",
    lastRun: "now",
    repo: "commander",
  },
  {
    name: "Build Desktop",
    command: "pnpm tauri build",
    type: "build",
    status: "idle",
    duration: "-",
    lastRun: "3h",
    repo: "commander",
  },
  {
    name: "Tests",
    command: "pnpm test",
    type: "test",
    status: "queued",
    duration: "-",
    lastRun: "yesterday",
    repo: "commander",
  },
  {
    name: "Lint",
    command: "pnpm lint",
    type: "lint",
    status: "success",
    duration: "00:42",
    lastRun: "30 min",
    repo: "commander",
  },
  {
    name: "Typecheck",
    command: "pnpm tsc --noEmit",
    type: "check",
    status: "failed",
    duration: "01:12",
    lastRun: "2h",
    repo: "commander",
  },
  {
    name: "Bundle Assets",
    command: "pnpm build:assets",
    type: "bundle",
    status: "idle",
    duration: "-",
    lastRun: "never",
    repo: "commander",
  },
  {
    name: "Dev Server",
    command: "pnpm dev",
    type: "run",
    status: "idle",
    duration: "-",
    lastRun: "20 min",
    repo: "billing-api",
  },
  {
    name: "Tests",
    command: "pnpm test",
    type: "test",
    status: "success",
    duration: "01:45",
    lastRun: "1h",
    repo: "billing-api",
  },
  {
    name: "Migrate DB",
    command: "pnpm prisma migrate dev",
    type: "build",
    status: "idle",
    duration: "-",
    lastRun: "2d",
    repo: "billing-api",
  },
  {
    name: "Seed",
    command: "pnpm prisma db seed",
    type: "run",
    status: "idle",
    duration: "-",
    lastRun: "2d",
    repo: "billing-api",
  },
  {
    name: "Storybook",
    command: "pnpm storybook",
    type: "run",
    status: "running",
    duration: "05:30",
    lastRun: "now",
    repo: "ui-kit",
  },
  {
    name: "Tests",
    command: "pnpm test",
    type: "test",
    status: "failed",
    duration: "00:58",
    lastRun: "1h",
    repo: "ui-kit",
  },
  {
    name: "Build",
    command: "pnpm build",
    type: "build",
    status: "idle",
    duration: "-",
    lastRun: "yesterday",
    repo: "ui-kit",
  },
]

export const liveExecutions: LiveExecution[] = [
  {
    repo: "commander",
    command: "Dev (Tauri)",
    pid: 42301,
    cpu: "38%",
    ram: "1.2 GB",
    logs: [
      { line: "[14:32:10] bundler ready", stream: "stdout" },
      { line: "[14:32:12] starting tauri dev", stream: "stdout" },
      { line: "[14:32:18] watching src/**/*", stream: "stdout" },
      { line: "[14:32:23] cache warmed in 4.1s", stream: "stdout" },
    ],
  },
  {
    repo: "billing-api",
    command: "Tests",
    pid: 42405,
    cpu: "12%",
    ram: "340 MB",
    logs: [
      { line: "[14:33:01] collecting tests…", stream: "stdout" },
      { line: "[14:33:04] running 48 tests", stream: "stdout" },
      { line: "[14:33:12] 32/48 passed", stream: "stdout" },
    ],
  },
  {
    repo: "ui-kit",
    command: "Storybook",
    pid: 42510,
    cpu: "22%",
    ram: "680 MB",
    logs: [
      { line: "[14:31:50] storybook starting", stream: "stdout" },
      { line: "[14:31:55] loaded 24 stories", stream: "stdout" },
      { line: "[14:31:58] serving on :6006", stream: "stdout" },
    ],
  },
]

export const runQueue: RunQueueItem[] = [
  {
    id: 1,
    name: "Build Desktop",
    repo: "commander",
    command: "pnpm build",
    commandType: "build",
    queuedAt: "14:10",
  },
  {
    id: 2,
    name: "Tests",
    repo: "billing-api",
    command: "pnpm test",
    commandType: "test",
    queuedAt: "14:11",
  },
  {
    id: 3,
    name: "Storybook",
    repo: "ui-kit",
    command: "pnpm storybook",
    commandType: "run",
    queuedAt: "14:12",
  },
]

export const pipelines: Pipeline[] = [
  {
    repo: "commander",
    steps: [
      { label: "Install deps", state: "done" },
      { label: "Setup env", state: "done" },
      { label: "Compile frontend", state: "running" },
      { label: "Package desktop", state: "pending" },
    ],
  },
  {
    repo: "billing-api",
    steps: [
      { label: "Install deps", state: "done" },
      { label: "Run migrations", state: "done" },
      { label: "Run tests", state: "running" },
      { label: "Deploy staging", state: "pending" },
    ],
  },
  {
    repo: "ui-kit",
    steps: [
      { label: "Install deps", state: "done" },
      { label: "Build tokens", state: "done" },
      { label: "Build components", state: "pending" },
      { label: "Publish", state: "pending" },
    ],
  },
]

export const executionHistory: ExecutionHistoryItem[] = [
  {
    id: 1,
    name: "Build Desktop",
    repo: "commander",
    status: "success",
    duration: "03:22",
    timestamp: "Today 14:12",
  },
  {
    id: 2,
    name: "Tests",
    repo: "billing-api",
    status: "success",
    duration: "01:45",
    timestamp: "Today 13:50",
  },
  {
    id: 3,
    name: "Lint",
    repo: "commander",
    status: "success",
    duration: "00:38",
    timestamp: "Today 13:30",
  },
  {
    id: 4,
    name: "Deploy Staging",
    repo: "billing-api",
    status: "failed",
    duration: "02:11",
    timestamp: "Today 12:05",
  },
  {
    id: 5,
    name: "Typecheck",
    repo: "ui-kit",
    status: "success",
    duration: "01:02",
    timestamp: "Today 11:40",
  },
  {
    id: 6,
    name: "Storybook Build",
    repo: "ui-kit",
    status: "success",
    duration: "01:55",
    timestamp: "Yesterday 18:20",
  },
  {
    id: 7,
    name: "Tests",
    repo: "commander",
    status: "failed",
    duration: "01:12",
    timestamp: "Yesterday 17:45",
  },
  {
    id: 8,
    name: "Build Desktop",
    repo: "commander",
    status: "success",
    duration: "03:18",
    timestamp: "Yesterday 16:30",
  },
]

export const historyStats: HistoryStats = {
  totalRuns: 18,
  successRate: "94%",
  avgDuration: "01:48",
}

export const selectedRunLogs: ExecutionLogLine[] = [
  { line: "[12:05:01] Starting deploy to staging…", stream: "stdout" },
  { line: "[12:05:03] Pulling latest from release/2026.01", stream: "stdout" },
  { line: "[12:05:08] Installing dependencies…", stream: "stdout" },
  { line: "[12:05:22] Dependencies installed", stream: "stdout" },
  { line: "[12:05:24] Running pre-deploy checks…", stream: "stdout" },
  { line: "[12:05:30] Typecheck passed", stream: "stdout" },
  { line: "[12:05:32] Lint passed", stream: "stdout" },
  { line: "[12:05:35] Running test suite…", stream: "stdout" },
  { line: "[12:06:48] 3 tests failed: auth.spec.ts", stream: "stderr" },
  { line: "[12:06:50] Deploy aborted — Tests failed", stream: "stderr" },
  { line: "[12:06:50] Exit code 1", stream: "stderr" },
]
