use crate::types::{
    Command, CommandStatus, CommandType, DashboardState, ExecutionHistoryItem, HistoryStats,
    LiveExecution, Pipeline, PipelineStep, Repository, RepositoryStatus, RunQueueItem, StepState,
};

pub fn empty_state() -> DashboardState {
    DashboardState {
        repositories: Vec::new(),
        commands: Vec::new(),
        live_executions: Vec::new(),
        run_queue: Vec::new(),
        pipelines: Vec::new(),
        execution_history: Vec::new(),
        history_stats: HistoryStats {
            total_runs: 0,
            success_rate: "0%".to_string(),
            avg_duration: "00:00".to_string(),
        },
    }
}

pub fn seed_state() -> DashboardState {
    DashboardState {
        repositories: vec![
            Repository {
                name: "commander".to_string(),
                path: "~/codes/commander".to_string(),
                branch: "main".to_string(),
                status: RepositoryStatus::Idle,
                tech: vec!["tauri".to_string(), "react".to_string(), "vite".to_string()],
                last_run: "-".to_string(),
                running: "-".to_string(),
            },
            Repository {
                name: "billing-api".to_string(),
                path: "~/codes/billing-api".to_string(),
                branch: "release/2026.01".to_string(),
                status: RepositoryStatus::Idle,
                tech: vec!["node".to_string(), "prisma".to_string()],
                last_run: "-".to_string(),
                running: "-".to_string(),
            },
            Repository {
                name: "ui-kit".to_string(),
                path: "~/codes/ui-kit".to_string(),
                branch: "design-refresh".to_string(),
                status: RepositoryStatus::Idle,
                tech: vec!["storybook".to_string(), "ts".to_string()],
                last_run: "-".to_string(),
                running: "-".to_string(),
            },
        ],
        commands: vec![
            Command {
                name: "Dev (Tauri)".to_string(),
                command: "pnpm tauri dev".to_string(),
                command_type: CommandType::Run,
                status: CommandStatus::Idle,
                duration: "-".to_string(),
                last_run: "-".to_string(),
                repo: "commander".to_string(),
            },
            Command {
                name: "Build Desktop".to_string(),
                command: "pnpm tauri build".to_string(),
                command_type: CommandType::Build,
                status: CommandStatus::Idle,
                duration: "-".to_string(),
                last_run: "-".to_string(),
                repo: "commander".to_string(),
            },
            Command {
                name: "Tests".to_string(),
                command: "pnpm test".to_string(),
                command_type: CommandType::Test,
                status: CommandStatus::Idle,
                duration: "-".to_string(),
                last_run: "-".to_string(),
                repo: "commander".to_string(),
            },
            Command {
                name: "Lint".to_string(),
                command: "pnpm lint".to_string(),
                command_type: CommandType::Lint,
                status: CommandStatus::Idle,
                duration: "-".to_string(),
                last_run: "-".to_string(),
                repo: "commander".to_string(),
            },
            Command {
                name: "Typecheck".to_string(),
                command: "pnpm tsc --noEmit".to_string(),
                command_type: CommandType::Check,
                status: CommandStatus::Idle,
                duration: "-".to_string(),
                last_run: "-".to_string(),
                repo: "commander".to_string(),
            },
            Command {
                name: "Bundle Assets".to_string(),
                command: "pnpm build:assets".to_string(),
                command_type: CommandType::Bundle,
                status: CommandStatus::Idle,
                duration: "-".to_string(),
                last_run: "-".to_string(),
                repo: "commander".to_string(),
            },
            Command {
                name: "Dev Server".to_string(),
                command: "pnpm dev".to_string(),
                command_type: CommandType::Run,
                status: CommandStatus::Idle,
                duration: "-".to_string(),
                last_run: "-".to_string(),
                repo: "billing-api".to_string(),
            },
            Command {
                name: "Tests".to_string(),
                command: "pnpm test".to_string(),
                command_type: CommandType::Test,
                status: CommandStatus::Idle,
                duration: "-".to_string(),
                last_run: "-".to_string(),
                repo: "billing-api".to_string(),
            },
            Command {
                name: "Migrate DB".to_string(),
                command: "pnpm prisma migrate dev".to_string(),
                command_type: CommandType::Build,
                status: CommandStatus::Idle,
                duration: "-".to_string(),
                last_run: "-".to_string(),
                repo: "billing-api".to_string(),
            },
            Command {
                name: "Seed".to_string(),
                command: "pnpm prisma db seed".to_string(),
                command_type: CommandType::Run,
                status: CommandStatus::Idle,
                duration: "-".to_string(),
                last_run: "-".to_string(),
                repo: "billing-api".to_string(),
            },
            Command {
                name: "Storybook".to_string(),
                command: "pnpm storybook".to_string(),
                command_type: CommandType::Run,
                status: CommandStatus::Idle,
                duration: "-".to_string(),
                last_run: "-".to_string(),
                repo: "ui-kit".to_string(),
            },
            Command {
                name: "Tests".to_string(),
                command: "pnpm test".to_string(),
                command_type: CommandType::Test,
                status: CommandStatus::Idle,
                duration: "-".to_string(),
                last_run: "-".to_string(),
                repo: "ui-kit".to_string(),
            },
            Command {
                name: "Build".to_string(),
                command: "pnpm build".to_string(),
                command_type: CommandType::Build,
                status: CommandStatus::Idle,
                duration: "-".to_string(),
                last_run: "-".to_string(),
                repo: "ui-kit".to_string(),
            },
        ],
        live_executions: vec![
            LiveExecution {
                repo: "commander".to_string(),
                command: "Dev (Tauri)".to_string(),
                pid: 42301,
                cpu: "38%".to_string(),
                ram: "1.2 GB".to_string(),
                logs: vec![
                    "[14:32:10] bundler ready".to_string(),
                    "[14:32:12] starting tauri dev".to_string(),
                    "[14:32:18] watching src/**/*".to_string(),
                    "[14:32:23] cache warmed in 4.1s".to_string(),
                ],
            },
            LiveExecution {
                repo: "billing-api".to_string(),
                command: "Tests".to_string(),
                pid: 42405,
                cpu: "12%".to_string(),
                ram: "340 MB".to_string(),
                logs: vec![
                    "[14:33:01] collecting tests...".to_string(),
                    "[14:33:04] running 48 tests".to_string(),
                    "[14:33:12] 32/48 passed".to_string(),
                ],
            },
            LiveExecution {
                repo: "ui-kit".to_string(),
                command: "Storybook".to_string(),
                pid: 42510,
                cpu: "22%".to_string(),
                ram: "680 MB".to_string(),
                logs: vec![
                    "[14:31:50] storybook starting".to_string(),
                    "[14:31:55] loaded 24 stories".to_string(),
                    "[14:31:58] serving on :6006".to_string(),
                ],
            },
        ],
        run_queue: vec![
            RunQueueItem {
                name: "Build Desktop".to_string(),
                repo: "commander".to_string(),
                eta: "~3 min".to_string(),
            },
            RunQueueItem {
                name: "Tests".to_string(),
                repo: "billing-api".to_string(),
                eta: "~8 min".to_string(),
            },
            RunQueueItem {
                name: "Storybook".to_string(),
                repo: "ui-kit".to_string(),
                eta: "~5 min".to_string(),
            },
        ],
        pipelines: vec![
            Pipeline {
                repo: "commander".to_string(),
                steps: vec![
                    PipelineStep {
                        label: "Install deps".to_string(),
                        state: StepState::Done,
                    },
                    PipelineStep {
                        label: "Setup env".to_string(),
                        state: StepState::Done,
                    },
                    PipelineStep {
                        label: "Compile frontend".to_string(),
                        state: StepState::Running,
                    },
                    PipelineStep {
                        label: "Package desktop".to_string(),
                        state: StepState::Pending,
                    },
                ],
            },
            Pipeline {
                repo: "billing-api".to_string(),
                steps: vec![
                    PipelineStep {
                        label: "Install deps".to_string(),
                        state: StepState::Done,
                    },
                    PipelineStep {
                        label: "Run migrations".to_string(),
                        state: StepState::Done,
                    },
                    PipelineStep {
                        label: "Run tests".to_string(),
                        state: StepState::Running,
                    },
                    PipelineStep {
                        label: "Deploy staging".to_string(),
                        state: StepState::Pending,
                    },
                ],
            },
            Pipeline {
                repo: "ui-kit".to_string(),
                steps: vec![
                    PipelineStep {
                        label: "Install deps".to_string(),
                        state: StepState::Done,
                    },
                    PipelineStep {
                        label: "Build tokens".to_string(),
                        state: StepState::Done,
                    },
                    PipelineStep {
                        label: "Build components".to_string(),
                        state: StepState::Pending,
                    },
                    PipelineStep {
                        label: "Publish".to_string(),
                        state: StepState::Pending,
                    },
                ],
            },
        ],
        execution_history: vec![
            ExecutionHistoryItem {
                id: 1,
                name: "Build Desktop".to_string(),
                repo: "commander".to_string(),
                status: CommandStatus::Success,
                duration: "03:22".to_string(),
                timestamp: "Today 14:12".to_string(),
            },
            ExecutionHistoryItem {
                id: 2,
                name: "Tests".to_string(),
                repo: "billing-api".to_string(),
                status: CommandStatus::Success,
                duration: "01:45".to_string(),
                timestamp: "Today 13:50".to_string(),
            },
            ExecutionHistoryItem {
                id: 3,
                name: "Lint".to_string(),
                repo: "commander".to_string(),
                status: CommandStatus::Success,
                duration: "00:38".to_string(),
                timestamp: "Today 13:30".to_string(),
            },
            ExecutionHistoryItem {
                id: 4,
                name: "Deploy Staging".to_string(),
                repo: "billing-api".to_string(),
                status: CommandStatus::Failed,
                duration: "02:11".to_string(),
                timestamp: "Today 12:05".to_string(),
            },
            ExecutionHistoryItem {
                id: 5,
                name: "Typecheck".to_string(),
                repo: "ui-kit".to_string(),
                status: CommandStatus::Success,
                duration: "01:02".to_string(),
                timestamp: "Today 11:40".to_string(),
            },
            ExecutionHistoryItem {
                id: 6,
                name: "Storybook Build".to_string(),
                repo: "ui-kit".to_string(),
                status: CommandStatus::Success,
                duration: "01:55".to_string(),
                timestamp: "Yesterday 18:20".to_string(),
            },
            ExecutionHistoryItem {
                id: 7,
                name: "Tests".to_string(),
                repo: "commander".to_string(),
                status: CommandStatus::Failed,
                duration: "01:12".to_string(),
                timestamp: "Yesterday 17:45".to_string(),
            },
            ExecutionHistoryItem {
                id: 8,
                name: "Build Desktop".to_string(),
                repo: "commander".to_string(),
                status: CommandStatus::Success,
                duration: "03:18".to_string(),
                timestamp: "Yesterday 16:30".to_string(),
            },
        ],
        history_stats: HistoryStats {
            total_runs: 18,
            success_rate: "94%".to_string(),
            avg_duration: "01:48".to_string(),
        },
    }
}
